### ISSUE TITLE
Is it intentional that ipbus 2.6.0 includes uhal-gui 2.3.0?

### ISSUE THREAD

**Issue by jhegeman** [ipbus/ipbus-software#113]
Hi,

While tracking down some unexpected differences in RPM version numbers, I noticed that the ipbus 2.6.0 release here:
  http://ipbus.web.cern.ch/ipbus/sw/release/2.6/repos/centos7_x86_64/base/RPMS/
contains (apart from the expected 2.6.0 RPMS) also some uhal-gui RPMs that carry version 2.3.0. Is this intentional?

Cheers,
Jeroen

**Comment by tswilliams** [comment]
Hi Jeroen,

Thanks for pointing this out. This was an oversight on my part - the main source code of `uhal/gui` has not changed since v2.3.0, but in any case the build & packaging makefile infrastructure changed in v2.6.0, so the version number certainly should be v2.6.0. I'll correct this now, and include the fixed RPM in the v2.6.1 release

Cheers,
Tom

**Comment by tswilliams** [comment]
Hi,

I've now released v2.6.1 that contains this fix; more information about upgrading to that release can be found at http://ipbus.web.cern.ch/ipbus/post/software_release_2_6_1/

Cheers,
Tom
