### ISSUE TITLE
Update of uhal compiler to C++ 14

### ISSUE THREAD

**Issue by fravera** [ipbus/ipbus-software#205]
Dear ipbus developers,
we are using your SW to develop the CMS Phase 2 tracker DAQ system.
We found an issue when using your library together with another one used to control the power supplies.
The power supply is controlled via ethernet and we use the boost::asio::ip::tcp::socket utils.
There are no issues while compiling the SW, but when we run it we get a crash at the instantiation of a socker object 
and gdb points to a problem in the boost library.
I manage to find a work around by recompiling uhal with -std=c++1y added to CXXFLAGS  in uhal/config/mfCommonDefs.mk
and I was wondering if you can consider updating also the official version.

Please, let me know.
Cheers,
Fabio

**Comment by tswilliams** [comment]
Hi,

> We found an issue when using your library together with another one used to control the power supplies.
The power supply is controlled via ethernet and we use the boost::asio::ip::tcp::socket utils.
There are no issues while compiling the SW, but when we run it we get a crash at the instantiation of a socker object
and gdb points to a problem in the boost library.
>  I manage to find a work around by recompiling uhal with -std=c++1y added to CXXFLAGS in uhal/config/mfCommonDefs.mk

Based on this description, I assume that the source of the problem was that different C++ standards were being used to compile uHAL, boost, and the Phase 2 tracker DAQ software. 

One of the reasons that we do not specify a particular C++ standard in the uHAL makefiles is that we support a range of operating systems and compilers, each of which have a different set of supported C++ standards; also, as you have discovered the standard used also needs to be compatible with that used by other software that is built against uHAL. However, the value of the `CXXFLAGS` variable can be overridden on the command-line when running `make`, without editing `uhal/config/mfCommonDefs.mk`. For example, in your case you can build uHAL with the '1y' standard using the following command: `make CXXFLAGS="-g -Wall -pedantic -O3 -MMD -MP -fPIC -std=c++1y"`

Cheers,
Tom

Cheers,
Tom
