### ISSUE TITLE
Error in buildindg the code (make command)

### ISSUE THREAD

**Issue by tonaspiuck** [ipbus/ipbus-software#237]
Hi, 

I have problem in the make step:

--First installing via YUM and build the code I got an error:

/usr/bin/ld: can't find -lcactus_extern_pugixml

--Second, I just couldn't overcome the problem so I try compiling and installing from source, and I got the next error:
ERROR: 'get-deps' failed while processing .../pbus-software/controlhub: rebar_abort

OS is Centos7

Does anyone can help me with this issue please?

**Comment by tswilliams** [comment]
Hi,

> --First installing via YUM and build the code I got an error:
> 
> /usr/bin/ld: can't find -lcactus_extern_pugixml

I assume you encountered this error when using the example makefile linked from https://ipbus.web.cern.ch/doc/user/html/software/uhalQuickTutorial.html    Is that correct? Sorry, that line of the makefile is out-of-date; it should now be `-lpugixml` rather than `-lcactus_extern_pugixml` - I've updated the file on the website accordingly. Can you see if making that change solves your problem?

Cheers,
Tom

**Comment by tonaspiuck** [comment]
Perfect, thank you very much!

Have a nice day!
